services:
  cluster-master:
    image: firasj/spark-docker-cluster
    container_name: cluster-master
    ports:
      - "8088:8088"
      - "4040:4040"
      - "19888:19888"
      - "9000:9000"
      - "9870:9870"
    volumes:
      - "./app:/app"
    networks:
      - spark-cluster
    depends_on:
      - cluster-slave-1
      - scylla-master
    hostname: cluster-master
    tty: true
    working_dir: /app
    mem_limit: 3g
    memswap_limit: 3g
    mem_reservation: 1g
    entrypoint: 
      - bash
      - /app/app.sh

  cluster-slave-1:
    image: firasj/spark-docker-cluster
    container_name: cluster-slave-1
    networks:
      - spark-cluster
    hostname: cluster-slave-1
    tty: true
    mem_limit: 3g
    memswap_limit: 3g
    mem_reservation: 1g

  cluster-slave-2:
    image: firasj/spark-docker-cluster
    container_name: cluster-slave-2
    networks:
      - spark-cluster
    depends_on:
      - cluster-slave-1
    hostname: cluster-slave-2
    tty: true
    mem_limit: 3g
    memswap_limit: 3g 
    mem_reservation: 1g

  scylla-master:
    image: scylladb/scylla
    container_name: scylla-master
    ports:
      - "7000:7000"
    networks:
      - spark-cluster
    mem_limit: 2g
    memswap_limit: 2g
    mem_reservation: 1g

networks:
  spark-cluster:
    driver: bridge